# Generated by Django 5.2 on 2025-06-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_alter_tutorprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_student_slot',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('student', 'slot'), name='unique_booking', violation_error_message='Вы уже забронировали этот слот'),
        ),
    ]
